"""Added IsVerifed Field

Revision ID: 313016260a9a
Revises: c1de2f22ae74
Create Date: 2024-12-30 13:09:16.807506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313016260a9a'
down_revision = 'c1de2f22ae74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('IsVerified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('IsVerified')

    # ### end Alembic commands ###
