"""Modified Users & Goals table

Revision ID: 6f399d36ad7f
Revises: 9ad3a40bad4e
Create Date: 2024-12-29 01:12:44.484925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f399d36ad7f'
down_revision = '9ad3a40bad4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('modules')
    op.drop_table('courses')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CreatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(sa.Column('UpdatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('UserID',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('GoalDescription',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('TargetDate',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PrimaryPurpose', sa.Enum('Career Upskill', 'Career Transition', 'Entrance Exams Support', name='primary_purpose'), nullable=False))
        batch_op.add_column(sa.Column('Bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('EducationStatus', sa.Enum('School', 'Undergraduate', 'Postgraduate', 'Professional', 'Other', name='education_status'), nullable=True))
        batch_op.add_column(sa.Column('Skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ProficiencyLevels', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('LearningStyle', sa.Enum('Visual', 'Auditory', 'Kinesthetic', 'Reading/Writing', name='learning_style'), nullable=True))
        batch_op.add_column(sa.Column('PreferredTopics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('StudySchedule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('DesiredJobTitle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('TargetIndustry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('TargetSalary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('UpdatedAt', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.alter_column('PreferredLanguage',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('English', 'Japanese', 'German', 'French', 'Hindi', 'Tamil', name='languages'),
               nullable=False)
        batch_op.alter_column('CreatedAt',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('PreferredLanguage',
               existing_type=sa.Enum('English', 'Japanese', 'German', 'French', 'Hindi', 'Tamil', name='languages'),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('UpdatedAt')
        batch_op.drop_column('TargetSalary')
        batch_op.drop_column('TargetIndustry')
        batch_op.drop_column('DesiredJobTitle')
        batch_op.drop_column('StudySchedule')
        batch_op.drop_column('PreferredTopics')
        batch_op.drop_column('LearningStyle')
        batch_op.drop_column('ProficiencyLevels')
        batch_op.drop_column('Skills')
        batch_op.drop_column('EducationStatus')
        batch_op.drop_column('Bio')
        batch_op.drop_column('PrimaryPurpose')

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('TargetDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('GoalDescription',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('UserID',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('UpdatedAt')
        batch_op.drop_column('CreatedAt')

    op.create_table('courses',
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('SkillTag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('CourseID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('modules',
    sa.Column('ModuleID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('SkillTag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['courses.CourseID'], name='modules_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModuleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reports',
    sa.Column('ReportID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportContent', mysql.JSON(), nullable=True),
    sa.Column('GeneratedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], name='reports_ibfk_1'),
    sa.PrimaryKeyConstraint('ReportID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
