"""Added GoalName field in goals table

Revision ID: 7e91aaab33ad
Revises: 9203c0438101
Create Date: 2025-01-04 19:00:43.580102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e91aaab33ad'
down_revision = '9203c0438101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('GoalName', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('GoalName')

    # ### end Alembic commands ###
