"""empty message

Revision ID: 9ad3a40bad4e
Revises: 
Create Date: 2024-12-28 00:02:27.743298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ad3a40bad4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('modules')
    op.drop_table('goals')
    op.drop_table('courses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('PasswordHash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('PreferredLanguage',
               existing_type=mysql.ENUM('English', 'Japanese', 'German', 'French', 'Hindi', 'Tamil'),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('CreatedAt',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('CreatedAt',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('PreferredLanguage',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('English', 'Japanese', 'German', 'French', 'Hindi', 'Tamil'),
               nullable=False)
        batch_op.alter_column('PasswordHash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('Email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    op.create_table('courses',
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('SkillTag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('CourseID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('goals',
    sa.Column('GoalID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GoalDescription', mysql.TEXT(), nullable=True),
    sa.Column('TargetDate', sa.DATE(), nullable=True),
    sa.Column('ProgressPercentage', mysql.FLOAT(), nullable=True),
    sa.Column('GoalType', mysql.ENUM('Entrance Exam', 'Career Switch', 'Upskill', 'Beginner'), nullable=False),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], name='goals_ibfk_1'),
    sa.PrimaryKeyConstraint('GoalID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('modules',
    sa.Column('ModuleID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CourseID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('Description', mysql.TEXT(), nullable=True),
    sa.Column('SkillTag', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ImageURL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['CourseID'], ['courses.CourseID'], name='modules_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ModuleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reports',
    sa.Column('ReportID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ReportContent', mysql.JSON(), nullable=True),
    sa.Column('GeneratedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['users.UserID'], name='reports_ibfk_1'),
    sa.PrimaryKeyConstraint('ReportID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
