"""Modified User Table

Revision ID: c1de2f22ae74
Revises: 6f399d36ad7f
Create Date: 2024-12-30 00:46:08.677337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1de2f22ae74'
down_revision = '6f399d36ad7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('PrimaryPurpose',
               existing_type=mysql.ENUM('Career Upskill', 'Career Transition', 'Entrance Exams Support'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('PrimaryPurpose',
               existing_type=mysql.ENUM('Career Upskill', 'Career Transition', 'Entrance Exams Support'),
               nullable=False)

    # ### end Alembic commands ###
